0.1-1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -584,15 +584,22 @@ PACKAGE_URL=
 ac_unique_file="DESCRIPTION"
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-ZMQ_LIBDIR
-ZMQ_INCLUDEDIR
-PKG_CONFIG
-GET_PKG_CONFIG
-ENABLE_INTERNAL_ZMQ
 EXT_LIBS
+EXTERNAL_ZMQ_LDFLAGS
+EXTERNAL_ZMQ_INCLUDE
+INTERNAL_ZMQ_LIBDIR
+INTERNAL_ZMQ_INCLUDEDIR
+ENABLE_INTERNAL_ZMQ
+SYSTEM_ZMQ_LIBDIR
+SYSTEM_ZMQ_INCLUDEDIR
+GET_SYSTEM_ZMQ
+GET_PKG_CONFIG
 ZMQ_POLLER
 ZMQ_LDFLAGS
 ZMQ_INCLUDE
+zmq_LIBS
+zmq_CFLAGS
+PKG_CONFIG
 target_alias
 host_alias
 build_alias
@@ -639,6 +646,9 @@ enable_internal_zmq
       ac_precious_vars='build_alias
 host_alias
 target_alias
+PKG_CONFIG
+zmq_CFLAGS
+zmq_LIBS
 ZMQ_INCLUDE
 ZMQ_LDFLAGS
 ZMQ_POLLER'
@@ -1252,6 +1262,9 @@ Optional Features:
   --enable-internal-zmq   Enable internal ZeroMQ, default no.
 
 Some influential environment variables:
+  PKG_CONFIG  path to pkg-config utility
+  zmq_CFLAGS  C compiler flags for zmq, overriding pkg-config
+  zmq_LIBS    linker flags for zmq, overriding pkg-config
   ZMQ_INCLUDE
   ZMQ_LDFLAGS
   ZMQ_POLLER  select
@@ -1713,42 +1726,301 @@ else
 fi
 
 
+GET_PKG_CONFIG="no"
+GET_SYSTEM_ZMQ="no"
+# pkg.m4 - Macros to locate and utilise pkg-config.            -*- Autoconf -*-
+#
+# Copyright © 2004 Scott James Remnant <scott@netsplit.com>.
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA.
+#
+# As a special exception to the GNU General Public License, if you
+# distribute this file as part of a program that contains a
+# configuration script generated by Autoconf, you may include it under
+# the same distribution terms that you use for the rest of that program.
+
+# PKG_PROG_PKG_CONFIG([MIN-VERSION])
+# ----------------------------------
 # PKG_PROG_PKG_CONFIG
-PKG_CONFIG="pkg-config"
-GET_PKG_CONFIG="not_ok"
-ZMQ_INCLUDEDIR=""
-ZMQ_LIBDIR=""
-if test "X$ENABLE_INTERNAL_ZMQ" = "Xno" ; then
-  ZMQ_INCLUDEDIR=`$PKG_CONFIG --variable=includedir libzmq`
-  ZMQ_LIBDIR=`$PKG_CONFIG --variable=libdir libzmq`
-  if test "X$ZMQ_INCLUDEDIR" != "X" -a "X$ZMQ_LIBDIR" != "X" ; then
-    GET_PKG_CONFIG="ok"
+
+# PKG_CHECK_EXISTS(MODULES, [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])
+#
+# Check to see whether a particular set of modules exists.  Similar
+# to PKG_CHECK_MODULES(), but does not set variables or print errors.
+#
+#
+# Similar to PKG_CHECK_MODULES, make sure that the first instance of
+# this or PKG_CHECK_MODULES is called, or make sure to call
+# PKG_CHECK_EXISTS manually
+# --------------------------------------------------------------
+
+
+
+# _PKG_CONFIG([VARIABLE], [COMMAND], [MODULES])
+# ---------------------------------------------
+# _PKG_CONFIG
+
+# _PKG_SHORT_ERRORS_SUPPORTED
+# -----------------------------
+# _PKG_SHORT_ERRORS_SUPPORTED
+
+
+# PKG_CHECK_MODULES(VARIABLE-PREFIX, MODULES, [ACTION-IF-FOUND],
+# [ACTION-IF-NOT-FOUND])
+#
+#
+# Note that if there is a possibility the first call to
+# PKG_CHECK_MODULES might not happen, you should be sure to include an
+# explicit call to PKG_PROG_PKG_CONFIG in your configure.ac
+#
+#
+# --------------------------------------------------------------
+# PKG_CHECK_MODULES
+
+
+
+if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
+	if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}pkg-config", so it can be a program name with args.
+set dummy ${ac_tool_prefix}pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
   fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $PKG_CONFIG" >&5
+$as_echo "$PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
 fi
 
-if test "X$GET_PKG_CONFIG" = "Xnot_ok" ; then
 
-  if ${ZMQ_INCLUDE+:} false; then :
+fi
+if test -z "$ac_cv_path_PKG_CONFIG"; then
+  ac_pt_PKG_CONFIG=$PKG_CONFIG
+  # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_path_ac_pt_PKG_CONFIG+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  case $ac_pt_PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_PKG_CONFIG="$ac_pt_PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_ac_pt_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+ac_pt_PKG_CONFIG=$ac_cv_path_ac_pt_PKG_CONFIG
+if test -n "$ac_pt_PKG_CONFIG"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_pt_PKG_CONFIG" >&5
+$as_echo "$ac_pt_PKG_CONFIG" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+  if test "x$ac_pt_PKG_CONFIG" = x; then
+    PKG_CONFIG=""
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    PKG_CONFIG=$ac_pt_PKG_CONFIG
+  fi
+else
+  PKG_CONFIG="$ac_cv_path_PKG_CONFIG"
+fi
+
+fi
+if test -n "$PKG_CONFIG"; then
+	_pkg_min_version=0.25
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking pkg-config is at least version $_pkg_min_version" >&5
+$as_echo_n "checking pkg-config is at least version $_pkg_min_version... " >&6; }
+	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	else
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+		PKG_CONFIG=""
+	fi
+
+fi
+if test "X$PKG_CONFIG" != "X" ; then
+  GET_PKG_CONFIG="yes"
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for zmq" >&5
+$as_echo_n "checking for zmq... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$zmq_CFLAGS"; then
+        pkg_cv_zmq_CFLAGS="$zmq_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libzmq >= 4.0.4\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libzmq >= 4.0.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_zmq_CFLAGS=`$PKG_CONFIG --cflags "libzmq >= 4.0.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$zmq_LIBS"; then
+        pkg_cv_zmq_LIBS="$zmq_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libzmq >= 4.0.4\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libzmq >= 4.0.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_zmq_LIBS=`$PKG_CONFIG --libs "libzmq >= 4.0.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        zmq_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libzmq >= 4.0.4"`
+        else
+	        zmq_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libzmq >= 4.0.4"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$zmq_PKG_ERRORS" >&5
+
+	GET_SYSTEM_ZMQ="no"
+elif test $pkg_failed = untried; then
+	GET_SYSTEM_ZMQ="no"
+else
+	zmq_CFLAGS=$pkg_cv_zmq_CFLAGS
+	zmq_LIBS=$pkg_cv_zmq_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	GET_SYSTEM_ZMQ="yes"
+fi
+fi
+
+SYSTEM_ZMQ_INCLUDEDIR=""
+SYSTEM_ZMQ_LIBDIR=""
+if test "X$GET_PKG_CONFIG" = "Xyes" -a "X$GET_SYSTEM_ZMQ" = "Xyes" -a "X$ENABLE_INTERNAL_ZMQ" = "Xno" ; then
+  SYSTEM_ZMQ_INCLUDEDIR=`$PKG_CONFIG --variable=includedir libzmq`
+  SYSTEM_ZMQ_LIBDIR=`$PKG_CONFIG --variable=libdir libzmq`
+fi
+
+INTERNAL_ZMQ_INCLUDEDIR="./zmqsrc/include"
+INTERNAL_ZMQ_LIBDIR="./"
+
+
+if ${ZMQ_INCLUDE+:} false; then :
 
 else
    ZMQ_INCLUDE=""
 fi
-  if test "X$ZMQ_INCLUDE" = "X" ; then
-    ZMQ_INCLUDE="-I./zmqsrc/include"
-  fi
+EXTERNAL_ZMQ_INCLUDE="${ZMQ_INCLUDE}"
 
-
-  if ${ZMQ_LDFLAGS+:} false; then :
+if ${ZMQ_LDFLAGS+:} false; then :
 
 else
    ZMQ_LDFLAGS=""
 fi
-  if test "X$ZMQ_LDFLAGS" = "X" ; then
-    ZMQ_LDFLAGS="-L./ -lzmq"
-  fi
+EXTERNAL_ZMQ_LDFLAGS="${ZMQ_LDFLAGS}"
+
+ZMQ_INCLUDE=""
+ZMQ_LDFLAGS=""
+if test "X$EXTERNAL_ZMQ_INCLUDE" != "X" -a "X$EXTERNAL_ZMQ_LDFLAGS" != "X" ; then
+  ZMQ_INCLUDE="${EXTERNAL_ZMQ_INCLUDE}"
+  ZMQ_LDFLAGS="${EXTERNAL_ZMQ_LDFLAGS}"
 else
-    ZMQ_INCLUDE="-I${ZMQ_INCLUDEDIR}"
-  ZMQ_LDFLAGS="-L${ZMQ_LIBDIR} -lzmq"
+  if test "X$ENABLE_INTERNAL_ZMQ" = "Xyes" ; then
+    ZMQ_INCLUDE="-I${INTERNAL_ZMQ_INCLUDEDIR}"
+    ZMQ_LDFLAGS="-L${INTERNAL_ZMQ_LIBDIR} -lzmq"
+  else
+    if test "X$SYSTEM_ZMQ_INCLUDEDIR" != "X" -a "X$SYSTEM_ZMQ_LIBDIR" != "X" ; then
+      ZMQ_INCLUDE="-I${SYSTEM_ZMQ_INCLUDEDIR}"
+      ZMQ_LDFLAGS="-L${SYSTEM_ZMQ_LIBDIR} -lzmq"
+    else
+      ZMQ_INCLUDE="-I${INTERNAL_ZMQ_INCLUDEDIR}"
+      ZMQ_LDFLAGS="-L${INTERNAL_ZMQ_LIBDIR} -lzmq"
+    fi
+  fi
 fi
 
 if test "$ZMQ_INCLUDE" != "-I./zmqsrc/include" -a "$ZMQ_LDFLAGS" != "-L./ -lzmq" ; then
@@ -1770,18 +2042,28 @@ fi
 echo " "
 echo "****************** Results of pbdZMQ package configure *****************"
 echo " "
+echo ">> GET_PKG_CONFIG = ${GET_PKG_CONFIG}"
+echo ">> GET_SYSTEM_ZMQ = ${GET_SYSTEM_ZMQ}"
+echo ">> PKG_CONFIG = ${PKG_CONFIG}"
+echo ">> SYSTEM_ZMQ_INCLUDEDIR = ${SYSTEM_ZMQ_INCLUDEDIR}"
+echo ">> SYSTEM_ZMQ_LIBDIR = ${SYSTEM_ZMQ_LIBDIR}"
+echo ">> ENABLE_INTERNAL_ZMQ = ${ENABLE_INTERNAL_ZMQ}"
+echo ">> INTERNAL_ZMQ_INCLUDEDIR = ${INTERNAL_ZMQ_INCLUDEDIR}"
+echo ">> INTERNAL_ZMQ_LIBDIR = ${INTERNAL_ZMQ_LIBDIR}"
+echo ">> EXTERNAL_ZMQ_INCLUDE = ${EXTERNAL_ZMQ_INCLUDE}"
+echo ">> EXTERNAL_ZMQ_LDFLAGS = ${EXTERNAL_ZMQ_LDFLAGS}"
 echo ">> ZMQ_INCLUDE = ${ZMQ_INCLUDE}"
 echo ">> ZMQ_LDFLAGS = ${ZMQ_LDFLAGS}"
-echo ">> ZMQ_POLLER = ${ZMQ_POLLER}"
 echo ">> EXT_LIBS = ${EXT_LIBS}"
-echo ">> ENABLE_INTERNAL_ZMQ = ${ENABLE_INTERNAL_ZMQ}"
-echo ">> GET_PKG_CONFIG = ${GET_PKG_CONFIG}"
-echo ">> PKG_CONFIG = ${PKG_CONFIG}"
-echo ">> ZMQ_INCLUDEDIR = ${ZMQ_INCLUDEDIR}"
-echo ">> ZMQ_LIBDIR = ${ZMQ_LIBDIR}"
+echo ">> ZMQ_POLLER = ${ZMQ_POLLER}"
 echo " "
 echo "************************************************************************"
 echo " "
+
+
+
+
+
 
 
 
